# ╔═══════════════════════════════════════════════════════════════╗
# ║                      NextHunt v1.0                            ║
# ║                  Для сервера AmixolPlex                       ║
# ║                                                               ║
# ║  Админ Амиксиль - лучший на свете,                           ║
# ║  Создал сервер для всех на планете!                          ║
# ║  Охота началась, игроки в азарте,                            ║
# ║  Победа близка на игровой карте!                             ║
# ║                                                               ║
# ║  Разработано с любовью для вашего проекта                    ║
# ╚═══════════════════════════════════════════════════════════════╝

telegram:
  # Токен бота от @BotFather
  token: "8410536115:AAEWz4l9PKCN-_7YyhXhAoZwvqjOXxCxCb8"

  # Имя бота (без @)
  username: "amixolobriganbot"

  # ID чата для отправки уведомлений
  chatId: 2113819244

settings:
  world:
    # Название мира, в котором будет проходить охота
    name: world

    # Минимальная координата X для телепортации цели
    minX: 400

    # Максимальная координата X для телепортации цели
    maxX: 2000

    # Минимальная координата Z для телепортации цели
    minZ: 400

    # Максимальная координата Z для телепортации цели
    maxZ: 2000

  # Время обратного отсчёта до начала охоты
  # Формат: число + буква (s - секунды, m - минуты, h - часы, d - дни)
  # Примеры: 30s, 5m, 1h, 2d
  countdown: 30s

  # Как часто показывать топ игроков по урону во время охоты
  # Формат такой же, как у countdown
  broadcastPeriod: 10s

  # Как часто обновлять координаты цели в боссбаре (в секундах)
  # Если сервер лагает, увеличьте значение до 1
  # Рекомендуемые значения: 0.05 (быстро) или 1 (медленно)
  coordinatesPeriod: 0.05

  # Сколько лучших игроков показывать в топе по урону
  topCount: 3

sounds:
  timer: BLOCK_NOTE_BLOCK_BELL:1.0:0.3
  start: ENTITY_ENDER_DRAGON_AMBIENT:1.0:0.7
  end: ENTITY_ENDER_DRAGON_DEATH:1.0:0.7

messages:
  # Префикс плагина, используется во всех сообщениях
  # Поддерживает HEX цвета в формате &#RRGGBB
  prefix: "&#FF7C00&l[&#FF8C1E&lʜ&#FF9B3D&lᴜ&#FFAB5B&lɴ&#FF942E&lᴛ&#FF7C00&l]"

  configReload: "%prefix% &fКонфиг перезагружен!"

  bossBar:
    # Текст боссбара во время обратного отсчёта
    # Плейсхолдеры: %time% - оставшееся время в формате M:SS
    countdown: "До начала охоты %time%"

    # Текст боссбара во время охоты
    # Плейсхолдеры: %name% - имя цели, %x% - координата X, %y% - Y, %z% - Z
    hunt: "Охота на игрока %name% | x: %x% y: %y% z: %z%"

  # Сообщение в чат при обратном отсчёте (каждую минуту)
  # Плейсхолдеры: %time% - оставшееся время, %prefix% - префикс плагина
  countdown: "%prefix% &fДо начала охоты осталось %time%"

  # Сообщение при завершении охоты
  # Плейсхолдеры: %prefix% - префикс плагина
  end: "%prefix% &fОхота завершена"

  # Сообщение при начале охоты
  # Плейсхолдеры: %prefix% - префикс плагина, %name% - имя цели
  start: "%prefix% &f✴ Охота на игрока &c&l%name%&f началась! Наносите урон и соревнуйтесь за звание лучшего охотника. Победитель получит &6ценные награды!"

  # Формат вывода топа игроков по урону
  # Каждая строка отправляется отдельным сообщением
  # Специальные плейсхолдеры:
  #   %toplist% - будет заменён на список топ игроков (используйте формат из topFormatted)
  #   %damage% - урон текущего игрока, которому показывается топ
  top:
    - " "
    - "&#ebcc34Топ по урону"
    - "%toplist%"
    - " "
    - "&#ebcc34▶ Ваш урон: %damage% &c❤"

  # Формат одной строки в топе игроков
  # Плейсхолдеры: %n% - место в топе, %name% - имя игрока, %d% - урон
  topFormatted: "&#ebcc34%n%. &f%name% &7◆ &f%d% &c❤"

  final:
    - "&#ebcc34Игроки, занявшие призовые места"
    - "%killer% - последний удар"