# ╔═══════════════════════════════════════════════════════════════╗
# ║                      NextHunt v1.0                            ║
# ║                  Для сервера AmixolPlex                       ║
# ║                                                               ║
# ║  Админ Амиксиль - лучший на свете,                           ║
# ║  Создал сервер для всех на планете!                          ║
# ║  Охота началась, игроки в азарте,                            ║
# ║  Победа близка на игровой карте!                             ║
# ║                                                               ║
# ║  Разработано с любовью для вашего проекта                    ║
# ╚═══════════════════════════════════════════════════════════════╝

telegram:
  # Токен бота от @BotFather
  token: "YOUR_BOT_TOKEN"

  # Имя бота (без @)
  username: "username"

  # ID чата для отправки уведомлений (может быть группой или личным чатом)
  chatId: 1234567890


settings:
  world:
    # Название мира, в котором будет проходить охота
    # Используйте точное имя мира, как в папке /world/ (например: "world", "world_nether")
    name: world

    # Минимальная координата X для случайной телепортации цели
    minX: 400

    # Максимальная координата X для случайной телепортации цели
    maxX: 2000

    # Минимальная координата Z для случайной телепортации цели
    minZ: 400

    # Максимальная координата Z для случайной телепортации цели
    maxZ: 2000

  # Время обратного отсчёта до начала охоты
  # Формат: число + буква (s - секунды, m - минуты, h - часы, d - дни)
  # Примеры: 30s, 5m, 1h, 2d
  countdown: 30s

  # Как часто показывать топ игроков по урону во время охоты
  # Используется для периодического вывода списка лидеров
  broadcastPeriod: 10s

  # Как часто обновлять координаты цели в боссбаре (в секундах)
  # Чем меньше значение — тем чаще обновляется позиция, но выше нагрузка на сервер
  # Рекомендуется: 0.05 (быстро) или 1 (медленно)
  coordinatesPeriod: 0.05

  # Сколько лучших игроков показывать в топе по урону
  # Например, 3 — будет показан топ-3 игроков
  topCount: 3


sounds:
  # Звук, проигрываемый каждую секунду при обратном отсчёте
  # Формат: SOUND:громкость:тональность
  # Пример: BLOCK_NOTE_BLOCK_BELL:1.0:0.3
  timer: BLOCK_NOTE_BLOCK_BELL:1.0:0.3

  # Звук, проигрываемый при начале охоты
  start: ENTITY_ENDER_DRAGON_AMBIENT:1.0:1.0

  # Звук, проигрываемый при завершении охоты
  end: ENTITY_ENDER_DRAGON_DEATH:1.0:1.0


messages:
  # Префикс плагина, отображается в начале всех сообщений
  # Поддерживает HEX цвета в формате &#RRGGBB
  prefix: "&#FF7C00&l[&#FF8C1E&lʜ&#FF9B3D&lᴜ&#FFAB5B&lɴ&#FF942E&lᴛ&#FF7C00&l]"

  # Сообщение при перезагрузке конфига
  # Плейсхолдеры: %prefix% — заменяется на префикс плагина
  configReload: "%prefix% &fКонфиг перезагружен!"

  bossBar:
    # Текст боссбара во время обратного отсчёта
    # Плейсхолдеры:
    #   %time% — оставшееся время в формате M:SS
    countdown: "До начала охоты %time%"

    # Текст боссбара во время активной охоты
    # Плейсхолдеры:
    #   %name% — имя цели
    #   %x%, %y%, %z% — координаты цели
    hunt: "Охота на игрока %name% | x: %x% y: %y% z: %z%"

  # Сообщение в чат во время обратного отсчёта
  # Отправляется каждую минуту (или чаще, если осталось меньше 5 секунд)
  # Плейсхолдеры:
  #   %time% — оставшееся время
  #   %prefix% — префикс плагина
  countdown: "%prefix% &fДо начала охоты осталось %time%"

  # Сообщение в чат при завершении охоты
  # Плейсхолдеры:
  #   %prefix% — префикс плагина
  end: "%prefix% &fОхота завершена"

  # Сообщение при старте охоты
  # Плейсхолдеры:
  #   %prefix% — префикс плагина
  #   %name% — имя выбранной цели
  start: "%prefix% &f✴ Охота на игрока &c&l%name%&f началась! Наносите урон и соревнуйтесь за звание лучшего охотника. Победитель получит &6ценные награды!"

  # Формат блока сообщений для отображения топа игроков
  # Каждый элемент списка = отдельное сообщение
  # Плейсхолдеры:
  #   %toplist% — заменяется на список лучших игроков (см. topFormatted)
  #   %damage% — урон текущего игрока
  #   %prefix% — префикс плагина
  top:
    - " "
    - "&#ebcc34Топ по урону"
    - "%toplist%"
    - " "
    - "&#ebcc34▶ Ваш урон: %damage% &c❤"

  # Формат одной строки в списке топа игроков
  # Плейсхолдеры:
  #   %n% — место игрока в топе
  #   %name% — ник игрока
  #   %d% — количество нанесённого урона
  topFormatted: "&#ebcc34%n%. &f%name% &7◆ &f%d% &c❤"

  final:
    # Заголовок финального топа после окончания охоты
    - "&#ebcc34Игроки, занявшие призовые места"

    # Строка с последним убийцей (кто нанёс финальный удар по цели)
    # Плейсхолдер: %killer% — имя игрока, нанёсшего финальный удар
    - "%killer% - последний удар"
